import { ArrowUpRight, CheckCircle2, Route, ShieldCheck, UsersRound } from 'lucide-react'
import Link from 'next/link'

export default function AboutPage() {
    return <main className="rk-about-page">
        <section className="rk-about-hero"><div className="rk-shell"><span className="rk-beta-badge">BETA</span><span className="rk-kicker">Why ReferKaro exists</span><h1>A clearer route<br />to a referral.</h1><p>ReferKaro is a two-sided career service where job seekers can request referrals for reviewed listings and employees can decide which candidates they are comfortable referring.</p></div></section>
        <section className="rk-section"><div className="rk-shell"><div className="rk-section-heading"><h2>Designed around a decision, not a promise.</h2><p>A referral request is not a guaranteed referral, interview, or job. The product exists to make the request, review, and outcome easier to follow for both people.</p></div><div className="rk-feature-grid"><article className="rk-feature-card"><Route className="rk-feature-icon" /><h3>Visible status</h3><p>Applications move through recorded states so job seekers can see where a request stands.</p></article><article className="rk-feature-card"><ShieldCheck className="rk-feature-icon" /><h3>Employment checks</h3><p>Employees must complete the implemented verification flow before creating listings.</p></article><article className="rk-feature-card"><UsersRound className="rk-feature-icon" /><h3>Two accountable roles</h3><p>Job seekers provide context; employees review it and record a decision.</p></article></div></div></section>
        <section className="rk-section rk-section-muted"><div className="rk-shell rk-about-flow"><div><span className="rk-kicker">What is live in beta</span><h2>The service today.</h2></div><ol><li><CheckCircle2 /><span><strong>Reviewed listings</strong>Only active, admin-approved openings appear in the jobs directory.</span></li><li><CheckCircle2 /><span><strong>Referral requests</strong>A job seeker can submit context, links, and a resume using one token.</span></li><li><CheckCircle2 /><span><strong>Employee decisions</strong>The referring employee can review, select, or decline a request.</span></li><li><CheckCircle2 /><span><strong>Tracked handoff</strong>Accepted flows use proxy-address and notification infrastructure found in the app.</span></li></ol></div></section>
        <section className="rk-section"><div className="rk-shell rk-beta-panel"><div><h2>Help shape the BETA.</h2><p>We are still validating the workflow, language, and operational details. Use the feedback channel when something feels unclear.</p></div><Link href="/feedback" className="rk-button rk-button-ink">Share feedback <ArrowUpRight size={16} /></Link></div></section>
    </main>
}
