import Link from 'next/link'

export default function DataProtectionPage() {
    return <main className="rk-legal-page"><div className="rk-shell rk-policy-layout">
        <header><span className="rk-kicker">DPDP notice</span><h1>How your data powers each step.</h1><p>Supplement to the Privacy Policy · Version 2026-09-22</p><div><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Use</Link></div></header>
        <article>
            <section><h2>The applicable framework</h2><p>The correct name is the <strong>Digital Personal Data Protection Act, 2023</strong>, commonly called the DPDP Act, together with the <strong>Digital Personal Data Protection Rules, 2025</strong>. The 14 November 2025 commencement notifications phase different provisions and rules into force on different dates. This notice is designed for the current transition period and does not claim certification by the Government or legal counsel.</p></section>
            <section><h2>Itemised notice</h2><ul><li>Account/profile data provides authentication, role-based workspaces, support, and fraud control.</li><li>Work email and OTP events prove access to an organisation-issued mailbox.</li><li>Employment evidence and AI output support provisional verification; admins make the official platform decision.</li><li>Job details and official URLs support listing checks and admin publication review.</li><li>Candidate profiles, resumes, and application notes are shared with the verified employee handling the selected listing.</li><li>Payment references and token ledgers provide purchases, reconciliation, refunds, and abuse prevention.</li><li>Operational logs support security, availability, debugging, and incident response.</li></ul></section>
            <section><h2>Consent and withdrawal</h2><p>The first signed-in workspace visit presents links to the Terms, Privacy Policy, and this notice and records the accepted version. Necessary processing is separated from optional marketing; no marketing consent is requested by this notice. To withdraw consent or close the account, email <a href="mailto:support@referkaro.app">support@referkaro.app</a> from the registered address. Withdrawal is as easy to initiate as acceptance, but it does not invalidate earlier lawful processing.</p></section>
            <section><h2>Access, correction, erasure, grievance, nomination</h2><p>Use the same support address to request a data summary, correction, completion, erasure, grievance review, or information about nomination. Include the registered email and request type, but do not email identity documents unless support specifically requests a secure method. ReferKaro will verify the requester and respond according to applicable timelines.</p></section>
            <section><h2>Automated checks</h2><p>An unsuccessful AI employment check exposes Resubmit and Request Manual Review. A successful AI check gives provisional referring access, while admin review stays pending. Resume-ranking assistance is limited and must not be treated as a hiring decision.</p></section>
            <section><h2>Official sources</h2><p><a href="https://www.indiacode.nic.in/handle/123456789/22037?locale=en" target="_blank" rel="noreferrer">India Code: DPDP Act, 2023</a><br /><a href="https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa" target="_blank" rel="noreferrer">MeitY: DPDP Rules, 2025 and corrigendum</a></p></section>
        </article>
    </div></main>
}
